#!/usr/bin/env bash
# Generates a production-ready .env from .env.example with fresh secrets.
# Run this ONCE on the production host. Resulting .env file is gitignored.
#
# Usage:
#   ./scripts/generate-prod-env.sh > .env
#   # then edit CORS_ALLOWED_ORIGINS / MINIO_PUBLIC_URL / APP_BRIDGE_PUBLIC_WS_URL
#   # to point at your real domain.

set -euo pipefail

EXAMPLE="$(dirname "$0")/../.env.example"
if [ ! -f "$EXAMPLE" ]; then
  echo "ERROR: .env.example not found at $EXAMPLE" >&2
  exit 1
fi

# Generate strong random secrets.
JWT_SECRET=$(openssl rand -base64 64 | tr -d '\n')
PG_PW=$(openssl rand -base64 24 | tr -d '\n/+=')
MINIO_PW=$(openssl rand -base64 24 | tr -d '\n/+=')
ADMIN_PW=$(openssl rand -base64 16 | tr -d '\n/+=')

cat <<EOF
# Generated by scripts/generate-prod-env.sh on $(date -u +%FT%TZ)
# Review and customize before deploying.

# ── Secrets (auto-generated) ─────────────────────────────────────────────────
JWT_SECRET=${JWT_SECRET}
POSTGRES_USER=dp
POSTGRES_PASSWORD=${PG_PW}
POSTGRES_DB=device_platform
MINIO_ROOT_USER=dp_minio
MINIO_ROOT_PASSWORD=${MINIO_PW}
ADMIN_USERNAME=admin
ADMIN_PASSWORD=${ADMIN_PW}

# ── Public URLs — REVIEW BEFORE DEPLOY ───────────────────────────────────────
# Replace example.com with your real domain.
CORS_ALLOWED_ORIGINS=https://console.example.com
MINIO_PUBLIC_URL=https://media.example.com
APP_BRIDGE_PUBLIC_WS_URL=wss://example.com/ws/agent

# ── Bind addresses (prod hardening) ──────────────────────────────────────────
# All internal services bound to loopback — only nginx on the host can reach
# them. Public traffic comes in through nginx → gateway (which is also on
# loopback; nginx upstream is 127.0.0.1:8080).
POSTGRES_BIND=127.0.0.1
REDIS_BIND=127.0.0.1
MINIO_BIND=127.0.0.1
GATEWAY_BIND=127.0.0.1
AUTH_BIND=127.0.0.1
DEVICE_BIND=127.0.0.1
SESSION_BIND=127.0.0.1
BRIDGE_BIND=127.0.0.1
AUTOMATION_BIND=127.0.0.1

# ── Retention ────────────────────────────────────────────────────────────────
RETENTION_ENABLED=true
RETENTION_DAYS=30
RETENTION_CRON=0 0 3 * * *

# ─────────────────────────────────────────────────────────────────────────────
# IMPORTANT:
#   - Initial admin password is ${ADMIN_PW}
#     Save this NOW; auth-service only seeds it on first boot.
#   - Rotate JWT_SECRET → all existing tokens are invalidated.
#   - Rotate POSTGRES_PASSWORD → also update inside Postgres via ALTER USER.
# ─────────────────────────────────────────────────────────────────────────────
EOF
